### ISSUE TITLE
Pre-built binaries in releases

### ISSUE THREAD

**Issue by Le0Developer** [Logicer16/pam-watchid#4]
Tried building on my fresh M4 mac mini but encountered a bunch of issues due to mismatching Swift versions.

- Operating System: Sequoia 15.1.1
- Xcode: Command Line Tools (/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk)
- Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)

<details>
<summary>Errors in case they are of any help</summary>

```
swiftc watchid-pam-extension.swift  -DSEQUOIASDK -o pam_watchid_x86_64.so -target x86_64-apple-darwin24.1.0 -emit-library
/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap:13:8: error: redefinition of module 'SwiftBridging'
11 | //===----------------------------------------------------------------------===//
12 | 
13 | module SwiftBridging {
   |        `- error: redefinition of module 'SwiftBridging'
14 |     header "bridging"
15 | 

/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap:13:8: note: previously defined here
11 | //===----------------------------------------------------------------------===//
12 | 
13 | module SwiftBridging {
   |        `- note: previously defined here
14 |     header "bridging"
15 | 

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/x86_64-apple-macos.swiftinterface:5:8: error: failed to build module 'CoreFoun
dation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0.25.3)', while this compiler is 'Apple Swift version 6.0.2 e
ffective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
    3 | // swift-module-flags: -target x86_64-apple-macos15.1 -target-variant x86_64-apple-ios18.1-macabi -enable-objc-interop -autolink-force-load -enable-library-evolution -module-link-name swiftFoundation 
-swift-version 5 -enforce-exclusivity=unchecked -O -library-level api -enable-upcoming-feature InferSendableFromCaptures -enable-bare-slash-regex -user-module-version 3107 -module-name Foundation -package-nam
e "\"FoundationPreview\""
    4 | import Combine
    5 | import CoreFoundation
      |        `- error: failed to build module 'CoreFoundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0.25
.3)', while this compiler is 'Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
    6 | import Darwin
    7 | import Dispatch

/Library/Developer/CommandLineTools/usr/include/swift/module.modulemap: 0:
/Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap: 0:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/LocalAuthentication.framework/Modules/LocalAuthentication.swiftmodule/x86_64-apple-macos.swiftinterface:5:8: error: failed to buil
d module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0.25.3)', while this compiler is 'Apple Swift v
ersion 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
 3 | // swift-module-flags: -target x86_64-apple-macos15.1 -target-variant x86_64-apple-ios18.1-macabi -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -O -library-
level api -enable-bare-slash-regex -user-module-version 1656.40.25 -module-name LocalAuthentication
 4 | import Combine
 5 | import Foundation
   |        `- error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0.25.3)', w
hile this compiler is 'Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
 6 | @_exported import LocalAuthentication
 7 | import Observation

watchid-pam-extension.swift:1:8: error: failed to build module 'LocalAuthentication'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.
7.43 clang-1600.0.25.3)', while this compiler is 'Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
  1 | import LocalAuthentication
    |        `- error: failed to build module 'LocalAuthentication'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0
.25.3)', while this compiler is 'Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
  2 | 
  3 | // MARK: (Re)define PAM constants here so we don't need to import .h files.
make: *** [all] Error 1

```

</details>

As I have pretty much 0 experience with Swift, I quickly gave up. Instead since I saw the CI was passing, I forked and made the CI [upload it's assets](https://github.com/Le0Developer/pam-watchid/commit/c9d2ce9cb85dff1a84187e878186cc6c66b7bbda), so that I could then [download the compiled binaries](https://github.com/Le0Developer/pam-watchid/actions/runs/11954795593). Which worked fine (after dequarantining it and almost bricking sudo, thanks Apple).

So, I was wondering if you could do "official" releases and publish pre-compiled binaries there for future me and others with no Swift experience?
Thanks!

**Comment by mostpinkest** [comment]
Thanks for the issue and sorry it's taken as long as it has for me to get back to you.

---

> * Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)

Correct me if I'm wrong, but it seems you've explicitly installed a second version of swift. Swift is bundled with Xcode / the Xcode command line tools. Unless you are developing / testing the language, or want to be on the bleeding edge, there is no need to install swift separately. Doing so has been known to cause issues like the one you're experiencing, resulting in errors like the ones you're seeing:

> ```
> this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0.25.3)', while this compiler is 'Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.
> ```

I don't blame someone with no experience for making that mistake. It is admittedly counter intuitive. I've updated the readme to hopefully clarify this.

For your own sake, I'd recommend you make sure your system is in a state where it can build programs like this locally, otherwise you may experience issues in the future.

---

As for the releases however, it would be far from ideal. Misuse of pluggable authentication modules posses a significant risk to a user's device and data, so I want, as much as possible, to eliminate the chance of a mistake being made. 

> after dequarantining it and almost bricking sudo

You yourself have experience with this risk. By building locally and maintaining control over the installation process, I can ensure the module is installed correctly and usable. This in part prompted the `enable` section of the makefile, allowing the entire installation process to be covered end-to-end, without the possibility of someone making a typo which bricks their system.

As a compromise though, I've added build artifacts to the CI pipeline so that if you (or someone else) still wishes to do so are able to download a precompiled binary from the most recent build. However, I'm still stopping short of making formal releases or documenting this as a supported installation method, due to risks posed.

> for future me and others with no Swift experience

I aim to make the installation as fool proof as possible. Experience, whilst nice to have, should not be required. Either the readme, build/installation script, or the system's own prompts (especially so on a brand new machine) should be holding your hand through the process, telling you each thing you need to do and how to do it. If at any point it doesn't work or is unclear in what needs to be done, that's a bug, and I am grateful when people [report it](https://github.com/Logicer16/pam-watchid/issues/new/choose), like you've done here. ❤️

**Comment by Le0Developer** [comment]
Thanks for the response!

As I said, I don't code in Swift, so I never installed it separately. It should be coming from the XCode CLT.
Might be homebrew installing it because it's a dependency of something I'm using, although `which swift` is pointing to the CLT and not homebrew 🤷

> As for the releases however, it would be far from ideal. Misuse of pluggable authentication modules posses a significant risk to a user's device and data, so I want, as much as possible, to eliminate the chance of a mistake being made.

[community/discussion#129761](https://github.com/orgs/community/discussions/129761) and github/roadmap#943 may be relevant integrity of builds if you ever want to go the path of "official" binaries.
My approach to not brinking myself was opening `/etc/pam.d/sudo_local` in vim (with sudo) and keeping it open. When I added the PAM module, I'd add the line to the file and save without quitting. Then do a `sudo whoami` in a separate terminal to see if sudo still worked. If it didn't, I'd remove the line and save the file to unbrick myself.

> As a compromise though, I've added build artifacts to the CI pipeline so that if you (or someone else) still wishes to do so are able to download a precompiled binary from the most recent build.

Thanks!

Just fyi, artifacts are temporary and deleted after 90 days. So there'd need to be a commit every 3 months to keep one of them laying around (or the user would fork and make a commit).

**Comment by mostpinkest** [comment]
> so I never installed it separately

Huh, odd. Guess it’s a mystery then 👻. Something to look into in the future when you need to. Could’ve been something else which didn’t clean up after itself.

Even if it was installed through Homebrew, it gets installed “keg-only”, meaning that unless you link to it yourself, it goes unused.

> [community/discussion#129761](https://github.com/orgs/community/discussions/129761) and https://github.com/github/roadmap/issues/943 may be relevant

Two steps ahead of you 😉.

> Just fyi, artifacts are temporary and deleted after 90 days.

Two steps ahead of you again 😉. Builds are scheduled every two months.
